extends: markdownlint/style/prettier
rules:
  MD013:
    line_length: 100
    code_blocks: false
    tables: false
  MD033: false  # Allow inline HTML
  MD041: false  # First line in file should be a top level header