name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_USERS: ${{ secrets.AUTH_USERS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint TypeScript/JavaScript
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python tools
        run: |
          pip install ruff pre-commit

      - name: Lint Python files
        run: ruff check .

      - name: Format check Python files
        run: ruff format --check .

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint-and-typecheck
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_USERS: ${{ secrets.AUTH_USERS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            .next/
            !.next/cache/
          retention-days: 1

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_USERS: ${{ secrets.AUTH_USERS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Run npm audit
        run: npm audit --audit-level=moderate

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python security tools
        run: pip install safety bandit

      - name: Check Python dependencies for vulnerabilities
        run: safety check --json

      - name: Run Python security linter
        run: bandit -r . -f json -o bandit-report.json || true